# Scattered Object Solution

[Settings]
AdjustExplosionForce = true									# Enables adjusting the incoming force from explosions from sources such as enchantments or spells.
AdjustProjectileForce = false								# Enables adjusting the incoming force from projectiles with the arrow, beam, flame or missile types.
AdjustShoutForce = true										# Enables adjusting the incoming force from shouts or projectiles with the cone type.
PushSoulGems = true											# Allow soul gems to be affected by incoming forces. (disabling may prevent you from disarming soul gem traps)
ForceMultiplier = 0.0										# The strength of the force that is going to be applied on references. (0.0 = 0%, 0.5 = 50%, 1.0 = 100%)

[Toggle]
ToggleHotKey = 55											# DXScanCode of the key, (55 = NUM*). You can find a list of them at https://www.creationkit.com/index.php?title=Input_Script.

[Notifications]
ShowNotifications = true									# Allows the game to display the notifications down below when enabled.
NotificationTextON = "Scattered Object Solution: ON"		# Text that is displayed when this plugin's functions are enabled. (text must be inbetween commas '"')
NotificationTextOFF = "Scattered Object Solution: OFF"		# Text that is displayed when this plugin's functions are disabled. (text must be inbetween commas '"')